name: ml-sft-trunc
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - lightgbm
  - matplotlib
  - numpy>=1.18
  - pandas>=1.0
  - pydot
  - pytables>=3.6.1
  - python>=3.6
  - scikit-learn
  - scikit-optimize
  - scipy
  - shap
  - seaborn
  - tensorflow-gpu>=2.0
